name: blue_async
description: Flutter plugin for auto connecting and communicating with Bluetooth Low Energy devices,
  on Android and iOS
version: 0.0.1
homepage: https://github.com/DoanpPhiHo/blue_async

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.hodoan.blue_async
        pluginClass: BlueAsyncPlugin
      ios:
        pluginClass: BlueAsyncPlugin